### ISSUE TITLE
Mapping of cell values does not happen on URI

### ISSUE THREAD

**Issue by jvsoest** [MaastrichtU-CDS/EPND-FAIRification#28] opened 2022-08-19 12:12 UTC
If I understand the code in mapDatasets.py correctly, the cell value (categorical mapping) happens on the rdfs:label of the option available in the Shape (SHACL definition), instead of the URI.
The SPARQL query involved here is in getCategories.py function getCategoryCode(). However it relies on proper matching of rdfs:labels, with some magic happening on the category string. This breaks in the EPND CS1 SHACL file for the APOE genotype.

Please change that it uses the actual URI (which should be unique) as value for mapping, instead of relative labels (which might change).

**Comment by jvsoest** [comment] 2022-08-19 12:12
@shashankmc only for after your holiday ;-)

**Comment by shashankmc** [comment] 2022-08-23 13:27
I tried to use this [fip file](https://raw.githubusercontent.com/MaastrichtU-CDS/EPND-FAIRification/case-study-1/fip/fip.ttl) from cs1 branch and ended up stuck at the cedar template editor. If I'm using the incorrect fip file, can you redirect me to the correct one please?

Error obtained -
`Traceback (most recent call last):`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__`
`return self.wsgi_app(environ, start_response)`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app`
`response = self.handle_exception(e)`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app`
`response = self.full_dispatch_request()`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request`
`rv = self.handle_user_exception(e)`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request`
`rv = self.dispatch_request()`
`File "../epndfairfication/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request`
`return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)`
`File "../EPND-FAIRification/management_webpage/flaskr/cedar_controller.py", line 71, in template`
`template = get_template()`
`File "../EPND-FAIRification/management_webpage/flaskr/cedar_controller.py", line 58, in get_template`
`cedar_location = __get_cedar_service().get_template_location()`
`File "../EPND-FAIRification/management_webpage/flaskr/services/cedar_service.py", line 33, in get_template_location`
`return self.__triplestore.select_sparql(query)[0]["cedar_template"]["value"]`
`IndexError: list index out of range`

**Comment by shashankmc** [comment] 2022-09-09 09:36
The error mentioned [above](https://github.com/MaastrichtU-CDS/EPND-FAIRification/issues/28#issuecomment-1224077527) was caused by issue  #32  and is resolved.

**Comment by shashankmc** [comment] 2022-09-19 08:45
Issue seems to be fixed on #33 . Requires validation, requested the same.

**Closed** 2022-11-29 15:43 UTC
Labels: bug
